### PR TITLE
docs: initial files for nextjs example

### PR DESCRIPTION
**Pull request by daine**
# Summary | Résumé
Example for NextJS integration. Only works with the SSR component (still unpublished at the moment).

`npm run build` works
~⚠️ Don't merge until the react-ssr canary package has been published~ package already exists!

[Zenhub ticket](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/816)

### CODE REVIEW

**Review by ethanWallace — DISMISSED** [review]

**Comment by melaniebmn** [comment]
@ethanWallace project should be ready for review now!

**Review by ethanWallace — CHANGES_REQUESTED** [review]
Looking good! Just one small thing I noticed in the header

**Review by ethanWallace — APPROVED** [review]
LGTM!

**Comment by melaniebmn** [comment]
Closing this in favor of [PR 16](https://github.com/cds-snc/gcds-examples/pull/16), as this PR includes commits that are not signed and therefore can't be merged.

**Pull request closed without merging**
